
package br.ufrpe.soa.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.3
 * Mon Aug 15 21:26:31 BRT 2022
 * Generated source version: 3.5.3
 */

@XmlRootElement(name = "decodeString", namespace = "http://soa.ufrpe.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "decodeString", namespace = "http://soa.ufrpe.br/")

public class DecodeString {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

