
package br.ufrpe.soa.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.3
 * Mon Aug 15 21:26:31 BRT 2022
 * Generated source version: 3.5.3
 */

@XmlRootElement(name = "encodeStringResponse", namespace = "http://soa.ufrpe.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "encodeStringResponse", namespace = "http://soa.ufrpe.br/")

public class EncodeStringResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

